require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/digitization_agsks", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # DigitizationAgsk. As you add validations to DigitizationAgsk, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DigitizationAgsk.create! valid_attributes
      get digitization_agsks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      digitization_agsk = DigitizationAgsk.create! valid_attributes
      get digitization_agsk_url(digitization_agsk)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_digitization_agsk_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      digitization_agsk = DigitizationAgsk.create! valid_attributes
      get edit_digitization_agsk_url(digitization_agsk)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DigitizationAgsk" do
        expect {
          post digitization_agsks_url, params: { digitization_agsk: valid_attributes }
        }.to change(DigitizationAgsk, :count).by(1)
      end

      it "redirects to the created digitization_agsk" do
        post digitization_agsks_url, params: { digitization_agsk: valid_attributes }
        expect(response).to redirect_to(digitization_agsk_url(DigitizationAgsk.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DigitizationAgsk" do
        expect {
          post digitization_agsks_url, params: { digitization_agsk: invalid_attributes }
        }.to change(DigitizationAgsk, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post digitization_agsks_url, params: { digitization_agsk: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested digitization_agsk" do
        digitization_agsk = DigitizationAgsk.create! valid_attributes
        patch digitization_agsk_url(digitization_agsk), params: { digitization_agsk: new_attributes }
        digitization_agsk.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the digitization_agsk" do
        digitization_agsk = DigitizationAgsk.create! valid_attributes
        patch digitization_agsk_url(digitization_agsk), params: { digitization_agsk: new_attributes }
        digitization_agsk.reload
        expect(response).to redirect_to(digitization_agsk_url(digitization_agsk))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        digitization_agsk = DigitizationAgsk.create! valid_attributes
        patch digitization_agsk_url(digitization_agsk), params: { digitization_agsk: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested digitization_agsk" do
      digitization_agsk = DigitizationAgsk.create! valid_attributes
      expect {
        delete digitization_agsk_url(digitization_agsk)
      }.to change(DigitizationAgsk, :count).by(-1)
    end

    it "redirects to the digitization_agsks list" do
      digitization_agsk = DigitizationAgsk.create! valid_attributes
      delete digitization_agsk_url(digitization_agsk)
      expect(response).to redirect_to(digitization_agsks_url)
    end
  end
end
